import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // AlgoVeda Design System
        "surface-bright": "#faf9f5",
        "surface-dim": "#dbdad6",
        "on-primary-fixed-variant": "#1d5031",
        "secondary-fixed-dim": "#eec058",
        "on-tertiary-container": "#e89ca5",
        "on-secondary-fixed-variant": "#5b4300",
        "secondary-fixed": "#ffdf9f",
        "inverse-on-surface": "#f2f1ed",
        outline: "#717971",
        "on-surface": "#1b1c1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#88bd95",
        "on-error-container": "#93000a",
        "surface-container": "#efeeea",
        "primary-container": "#1a4d2e",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#380b15",
        "surface-container-high": "#e9e8e4",
        "tertiary-fixed": "#ffd9dd",
        "error-container": "#ffdad6",
        "inverse-primary": "#9dd3aa",
        "surface-container-highest": "#e3e2df",
        "on-primary-fixed": "#00210e",
        "surface-container-low": "#f5f4f0",
        surface: "#faf9f5",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#30312e",
        error: "#ba1a1a",
        "on-surface-variant": "#414942",
        primary: "#00361a",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb2bb",
        "on-secondary-fixed": "#261a00",
        secondary: "#795900",
        "on-background": "#1b1c1a",
        tertiary: "#4f1c26",
        "on-tertiary-fixed-variant": "#6e353e",
        "primary-fixed-dim": "#9dd3aa",
        "on-secondary-container": "#755700",
        "primary-fixed": "#b8f0c5",
        "outline-variant": "#c1c9bf",
        "surface-variant": "#e3e2df",
        "on-primary": "#ffffff",
        "surface-tint": "#366847",
        "secondary-container": "#fece65",
        "tertiary-container": "#6a323b",
        background: "#faf9f5",
        // Extended semantic colors
        "av-green": "#1A4D2E",
        "av-gold": "#D4A843",
        "av-up": "#16A34A",
        "av-down": "#DC2626",
        "av-bg": "#F7F6F2",
        "av-text": "#0F1A14",
        "av-text-secondary": "#4A5568",
        "av-muted": "#94A3B8",
        "av-border": "#E8E6DF",
        "av-dark": "#0F1A14",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Playfair Display"', "serif"],
        ui: ["Syne", "sans-serif"],
        body: ['"DM Sans"', "sans-serif"],
        data: ['"DM Mono"', "monospace"],
        serif: ['"Playfair Display"', "serif"],
        mono: ['"DM Mono"', "monospace"],
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.04), 0 8px 24px rgba(26,77,46,0.06)",
        elevated: "0 4px 6px rgba(0,0,0,0.03), 0 16px 48px rgba(26,77,46,0.10)",
        glow: "0 0 0 3px rgba(26,77,46,0.15)",
      },
      backgroundImage: {
        "mesh-gradient":
          "radial-gradient(at 0% 0%, hsla(145,28%,91%,1) 0, transparent 50%), radial-gradient(at 100% 0%, hsla(42,45%,90%,1) 0, transparent 50%), radial-gradient(at 100% 100%, hsla(145,28%,95%,1) 0, transparent 50%), radial-gradient(at 0% 100%, hsla(42,45%,95%,1) 0, transparent 50%)",
      },
      animation: {
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 1.5s infinite",
        "fade-in": "fadeIn 0.2s ease-out",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
